/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conversor_de_moedas_java;

public class App {
    public static void main(String[] args) {

        AppMainFrame app = new AppMainFrame();
        app.setVisible(true);
    }
}
